version: '3.7'

services:
  user-service:
    image: akhilja/user-service:0.0.3-RELEASE
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: feedback_db
      RDS_USERNAME: root
      RDS_PASSWORD: password
      DATABASE_URL: jdbc:mysql://mysql:3306/feedback_db
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/feedback_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: feedback_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

volumes:
  mysql-database-data-volume:
